### ISSUE TITLE
Printing a string with placeholder failure

### ISSUE THREAD

**Issue by rumkin** [zamfofex/v-wasm#2]
The next code doesn't work:

```v
fn greet() {
	name := 'World'
	println('Hello, $name!')
}

greet()
```

It returns an error:

```text
ReferenceError: tos3 is not defined
    at test (eval at <anonymous> (https://v-wasm.now.sh/index.js:1:192605), <anonymous>:45:11)
    at eval (eval at <anonymous> (https://v-wasm.now.sh/index.js:1:192605), <anonymous>:50:3)
    at eval (eval at <anonymous> (https://v-wasm.now.sh/index.js:1:192605), <anonymous>:51:4)
    at eval (eval at <anonymous> (https://v-wasm.now.sh/index.js:1:192605), <anonymous>:55:3)
    at HTMLButtonElement.<anonymous> (https://v-wasm.now.sh/index.js:1:192643)
```

In the same time output of a variable or a string works fine.

**Comment by zamfofex** [comment]
Hello! :wave: Thank you so much for having bothered to take the time to file an issue, I do really appreciate it! :tada:

This used to be a problem with the JS backend in V back when I wrote this tool. It is actually fixed by now, though, so all I need to do is to update the V version used for the website.

And in fact, I have actually done just that yesterday after you opened this issue! I also made some other changes, such as using Wasmer instead of Emscripten.

I’m not going to close this just yet, though, as I haven’t reflected the changes to the repo yet, but I wanted to mention that it should be fixed on [the website] now! Please do feel free to try it out and report any other issues you might run into.

[the website]: https://v-wasm.now.sh

**Comment by rumkin** [comment]
I can confirm, it works fine now. Thanks for fixing this!
